"""Add measurement suffix and thousands

Revision ID: 10229b767711
Revises: c2d79d2ae74d
Create Date: 2021-06-09 17:09:52.152812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10229b767711"
down_revision = "c2d79d2ae74d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurements", sa.Column("suffix", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "measurements", sa.Column("thousand_fold", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "thousand_fold")
    op.drop_column("measurements", "suffix")
    # ### end Alembic commands ###
