"""Add event user roles

Revision ID: 6ad5e2929436
Revises: 95f774beeafc
Create Date: 2021-12-30 11:56:37.123083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ad5e2929436"
down_revision = "95f774beeafc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_have_event_roles",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("collaborator", "viewer"), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_users_have_event_roles_event_id_events"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_have_event_roles_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "user_id", name=op.f("pk_users_have_event_roles")
        ),
    )
    op.create_index(
        op.f("ix_users_have_event_roles_event_id"),
        "users_have_event_roles",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_have_event_roles_user_id"),
        "users_have_event_roles",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("users_have_event_roles")
