"""Add request_logs

Revision ID: 45909c277331
Revises: 6229b91ab6ba
Create Date: 2021-05-14 12:33:21.783873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "45909c277331"
down_revision = "6229b91ab6ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("remote_addr", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Float(precision=4), nullable=True),
        sa.Column("item_type", sa.String(length=255), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_logs_user_id"), "request_logs", ["user_id"], unique=False
    )
    op.drop_column("recipes", "is_draft")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column(
            "is_draft",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("request_logs")
    # ### end Alembic commands ###
