"""Add main photo

Revision ID: c053595974c4
Revises: 98b27ce5f559
Create Date: 2021-11-26 17:14:35.926895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c053595974c4"
down_revision = "98b27ce5f559"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("is_main", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "is_main")
    # ### end Alembic commands ###
