"""Add portion count to recipe

Revision ID: 6229b91ab6ba
Revises: 8e467f58dae6
Create Date: 2021-05-10 21:24:28.470221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6229b91ab6ba"
down_revision = "8e467f58dae6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("portion_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "portion_count")
    # ### end Alembic commands ###
