"""Add daily plans

Revision ID: b673757d8c36
Revises: 26993eab0131
Create Date: 2021-04-20 23:38:29.911322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b673757d8c36"
down_revision = "26993eab0131"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_plans_created_by"), "daily_plans", ["created_by"], unique=False
    )
    op.create_table(
        "daily_plans_have_recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("daily_plan_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["daily_plan_id"], ["daily_plans.id"]),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_plans_have_recipes_daily_plan_id"),
        "daily_plans_have_recipes",
        ["daily_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_plans_have_recipes_recipe_id"),
        "daily_plans_have_recipes",
        ["recipe_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("daily_plans_have_recipes")
    op.drop_table("daily_plans")
