"""Add missing foreign key

Revision ID: 3f03f6752386
Revises: 2e4f3a3214d8
Create Date: 2021-05-10 16:22:36.180908

"""
from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f03f6752386"
down_revision = "2e4f3a3214d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_dailyplans_events", "daily_plans", "events", ["event_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_dailyplans_events", "daily_plans", type_="foreignkey")
    # ### end Alembic commands ###
