"""Add measurement sorting priority

Revision ID: d1621395aa93
Revises: e5512c33b7f9
Create Date: 2021-10-19 13:43:59.639660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1621395aa93"
down_revision = "e5512c33b7f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurements",
        sa.Column("sorting_priority", sa.Integer(), server_default="0", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "sorting_priority")
    # ### end Alembic commands ###
