"""Add ingredient categories

Revision ID: 964fdad8ef3d
Revises: b673757d8c36
Create Date: 2021-04-25 17:58:43.777939

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "964fdad8ef3d"
down_revision = "b673757d8c36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("ingredients", sa.Column("category_id", sa.Integer()))
    op.create_foreign_key(
        "fk_ingredient_category",
        "ingredients",
        "ingredient_categories",
        ["category_id"],
        ["id"],
    )
    op.create_unique_constraint("uq_measurement_name", "measurements", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_measurement_name", "measurements", type_="unique")
    op.drop_constraint("fk_ingredient_category", "ingredients", type_="foreignkey")
    op.drop_column("ingredients", "category_id")
    op.drop_table("ingredient_categories")
    # ### end Alembic commands ###
