"""Add user recipe reactions

Revision ID: 54307bd50389
Revises: 1b0f7ab86df8
Create Date: 2021-05-02 14:38:46.564196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54307bd50389"
down_revision = "1b0f7ab86df8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_have_recipes_reaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_have_recipes_reaction_recipe_id"),
        "users_have_recipes_reaction",
        ["recipe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_have_recipes_reaction_user_id"),
        "users_have_recipes_reaction",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_have_recipes_reaction")
    # ### end Alembic commands ###
