"""Add ingredients and recipes

Revision ID: eed4b237589f
Revises: 9973a062e3ed
Create Date: 2021-04-19 16:51:36.483312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eed4b237589f"
down_revision = "9973a062e3ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("measurement", sa.Enum("gram", "kus"), nullable=False),
        sa.Column("calorie", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("sugar", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("fat", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("protein", sa.Float(), server_default=sa.text("'0'"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingredients_created_by"), "ingredients", ["created_by"], unique=False
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipes_created_by"), "recipes", ["created_by"], unique=False
    )
    op.create_table(
        "recipes_have_ingredients",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"]),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"]),
        sa.PrimaryKeyConstraint("recipe_id", "ingredient_id"),
    )
    op.create_index(
        op.f("ix_recipes_have_ingredients_ingredient_id"),
        "recipes_have_ingredients",
        ["ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipes_have_ingredients_recipe_id"),
        "recipes_have_ingredients",
        ["recipe_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     op.f("ix_recipes_have_ingredients_recipe_id"),
    #     table_name="recipes_have_ingredients",
    # )
    # op.drop_index(
    #     op.f("ix_recipes_have_ingredients_ingredient_id"),
    #     table_name="recipes_have_ingredients",
    # )
    op.drop_table("recipes_have_ingredients")
    # op.drop_index(op.f("ix_recipes_created_by"), table_name="recipes")
    op.drop_table("recipes")
    # op.drop_index(op.f("ix_ingredients_created_by"), table_name="ingredients")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
