"""Add label visible name

Revision ID: c277f316b2f7
Revises: 61144713de5c
Create Date: 2021-09-26 23:50:07.364542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c277f316b2f7"
down_revision = "61144713de5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "labels", sa.Column("visible_name", sa.String(length=80), nullable=True)
    )
    op.create_unique_constraint("uq_label_visible_name", "labels", ["visible_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_label_visible_name", "labels", type_="unique")
    op.drop_column("labels", "visible_name")
    # ### end Alembic commands ###
