"""Update roles model

Revision ID: 9e892e701545
Revises: d2e3a789a0e7
Create Date: 2021-11-21 10:47:57.113563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e892e701545"
down_revision = "d2e3a789a0e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("permissions", sa.UnicodeText(), nullable=True))
    op.add_column(
        "roles",
        sa.Column(
            "update_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.execute(
        """
        UPDATE roles
        SET permissions='manage-application,manage-users,login-as,see-debug,see-other,edit-other'
        WHERE name='admin';
        """
    )
    op.execute(
        """
        UPDATE roles
        SET permissions='manage-application,see-other,edit-other'
        WHERE name='application-manager';
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "update_datetime")
    op.drop_column("roles", "permissions")
    # ### end Alembic commands ###
