"""Add allow_multiple in label categories

Revision ID: 34958ef8528c
Revises: d1621395aa93
Create Date: 2021-10-25 22:54:57.456723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34958ef8528c"
down_revision = "d1621395aa93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_categories", sa.Column("allow_multiple", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("label_categories", "allow_multiple")
    # ### end Alembic commands ###
