"""Add missing event columns

Revision ID: 802a72a2ecb3
Revises: 3f03f6752386
Create Date: 2021-05-10 16:48:02.520229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "802a72a2ecb3"
down_revision = "3f03f6752386"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("name", sa.String(length=80), nullable=True))
    op.add_column("events", sa.Column("date_from", sa.Date(), nullable=True))
    op.add_column("events", sa.Column("date_to", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "date_to")
    op.drop_column("events", "date_from")
    op.drop_column("events", "name")
    # ### end Alembic commands ###
