"""Add ingredient measured

Revision ID: a043cfce4d72
Revises: 7a51dee13600
Create Date: 2021-06-08 19:18:11.094676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a043cfce4d72"
down_revision = "7a51dee13600"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes_have_ingredients",
        sa.Column("is_measured", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes_have_ingredients", "is_measured")
    # ### end Alembic commands ###
