"""Update user to Flask-Security-Too

Revision ID: df9f4da70856
Revises: eed4b237589f
Create Date: 2021-04-19 19:26:14.838338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9f4da70856'
down_revision = 'eed4b237589f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('tf_phone_number', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('tf_primary_method', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('tf_totp_secret', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('us_phone_number', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('us_totp_secrets', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_username', 'user', ['username'])
    op.create_unique_constraint('uq_fs_uniqiufier', 'user', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user', type_='unique')
    # op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'us_totp_secrets')
    op.drop_column('user', 'us_phone_number')
    op.drop_column('user', 'update_datetime')
    op.drop_column('user', 'tf_totp_secret')
    op.drop_column('user', 'tf_primary_method')
    op.drop_column('user', 'tf_phone_number')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'fs_uniquifier')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'create_datetime')
    # ### end Alembic commands ###
