"""Add comment to ingredient in recipe

Revision ID: 7a51dee13600
Revises: 45909c277331
Create Date: 2021-06-06 17:51:36.734827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a51dee13600"
down_revision = "45909c277331"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes_have_ingredients",
        sa.Column("comment", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes_have_ingredients", "comment")
    # ### end Alembic commands ###
