"""Simplify user

Revision ID: 35b8ac00b5d2
Revises: 31068afb5695
Create Date: 2021-04-20 22:53:02.589903

"""
from alembic import op
# import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "35b8ac00b5d2"
down_revision = "31068afb5695"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "active", existing_type=mysql.TINYINT(display_width=1), nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "active", existing_type=mysql.TINYINT(display_width=1), nullable=True
    )
    # ### end Alembic commands ###
