"""Add more columns to recipe and ingredient

Revision ID: 27bb148ce353
Revises: 86031807390d
Create Date: 2021-05-03 14:48:26.814132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "27bb148ce353"
down_revision = "86031807390d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingredients", sa.Column("gluten_free", sa.Boolean(), nullable=True))
    op.add_column("ingredients", sa.Column("is_vegan", sa.Boolean(), nullable=True))
    op.add_column(
        "ingredients", sa.Column("is_vegetarian", sa.Boolean(), nullable=True)
    )
    op.add_column("ingredients", sa.Column("lactose_free", sa.Boolean(), nullable=True))
    op.alter_column(
        "ingredients", "measurement_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.add_column("recipes", sa.Column("is_draft", sa.Boolean(), nullable=True))
    op.add_column("recipes", sa.Column("is_hidden", sa.Boolean(), nullable=True))
    op.drop_column("recipes", "is_public")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column(
            "is_public",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("recipes", "is_hidden")
    op.drop_column("recipes", "is_draft")
    op.alter_column(
        "ingredients", "measurement_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.drop_column("ingredients", "lactose_free")
    op.drop_column("ingredients", "is_vegetarian")
    op.drop_column("ingredients", "is_vegan")
    op.drop_column("ingredients", "gluten_free")
    # ### end Alembic commands ###
