"""empty message

Revision ID: 86031807390d
Revises: 06bdf14c5de1
Create Date: 2021-05-02 21:53:46.303870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86031807390d"
down_revision = "06bdf14c5de1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "recipes", "recipe_categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipes", type_="foreignkey")
    op.drop_column("recipes", "category_id")
    # ### end Alembic commands ###
