"""Add OAuth

Revision ID: 95f774beeafc
Revises: 5eca4d09a9d9
Create Date: 2021-12-09 10:42:09.601893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95f774beeafc"
down_revision = "5eca4d09a9d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flask_dance_oauth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("token", sa.JSON(), nullable=False),
        sa.Column("provider_user_id", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_flask_dance_oauth_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flask_dance_oauth")),
        sa.UniqueConstraint(
            "provider_user_id", name=op.f("uq_flask_dance_oauth_provider_user_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flask_dance_oauth")
    # ### end Alembic commands ###
