"""Add tips

Revision ID: 982f6f2cd912
Revises: 097c679b21fc
Create Date: 2021-07-06 14:18:27.020811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "982f6f2cd912"
down_revision = "097c679b21fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tips_created_by"), "tips", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tips_created_by"), table_name="tips")
    op.drop_table("tips")
    # ### end Alembic commands ###
