"""Add meal type enum

Revision ID: c2d79d2ae74d
Revises: a043cfce4d72
Create Date: 2021-06-09 11:09:54.938963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2d79d2ae74d"
down_revision = "a043cfce4d72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_plans_have_recipes",
        sa.Column(
            "meal_type",
            sa.Enum(
                "snídaně",
                "dopolední svačina",
                "oběd",
                "odpolední svačina",
                "večeře",
                "programové",
                "jiné",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_plans_have_recipes", "meal_type")
    # ### end Alembic commands ###
