"""Add attendee portion type connection

Revision ID: e0a86e5d519e
Revises: 3b4cb874032b
Create Date: 2022-08-04 10:10:40.903438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e0a86e5d519e"
down_revision = "3b4cb874032b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendees", sa.Column("portion_type_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_attendees_portion_type_id_portion_types"),
        "attendees",
        "portion_types",
        ["portion_type_id"],
        ["id"],
    )
    op.drop_column("attendees", "portion_size_ratio")
    op.alter_column(
        "daily_plans_have_recipes",
        "portion_count",
        existing_type=mysql.FLOAT(),
        nullable=False,
    )
    op.drop_index("name", table_name="measurements")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("name", "measurements", ["name"], unique=False)
    op.alter_column(
        "daily_plans_have_recipes",
        "portion_count",
        existing_type=mysql.FLOAT(),
        nullable=True,
    )
    op.add_column(
        "attendees", sa.Column("portion_size_ratio", mysql.FLOAT(), nullable=True)
    )
    op.drop_constraint(
        op.f("fk_attendees_portion_type_id_portion_types"),
        "attendees",
        type_="foreignkey",
    )
    op.drop_column("attendees", "portion_type_id")
    # ### end Alembic commands ###
