"""Add recipe source

Revision ID: a80362ef1e35
Revises: 6ad5e2929436
Create Date: 2022-02-01 09:47:59.005607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a80362ef1e35"
down_revision = "6ad5e2929436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "source")
    # ### end Alembic commands ###
