"""Add portion types

Revision ID: 3b4cb874032b
Revises: 71405264f03b
Create Date: 2022-08-03 17:22:36.602526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3b4cb874032b"
down_revision = "71405264f03b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portion_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_portion_types_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portion_types")),
    )
    op.create_index(
        op.f("ix_portion_types_created_by"),
        "portion_types",
        ["created_by"],
        unique=False,
    )


def downgrade():
    op.drop_table("portion_types")
