"""Add event portion type

Revision ID: 2ddeb48032ef
Revises: 32c01362370f
Create Date: 2022-08-05 08:24:59.375510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ddeb48032ef"
down_revision = "32c01362370f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_has_portion_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("portion_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_has_portion_type_events_id_events"),
        ),
        sa.ForeignKeyConstraint(
            ["portion_type_id"],
            ["portion_types.id"],
            name=op.f("fk_event_has_portion_type_portion_type_id_portion_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_has_portion_type")),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("event_has_portion_type")
