"""Add daily plan tasks

Revision ID: 71380acda9ec
Revises: 642a49893a64
Create Date: 2022-05-27 10:03:51.651269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71380acda9ec"
down_revision = "642a49893a64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_plan_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("daily_plan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["daily_plan_id"],
            ["daily_plans.id"],
            name=op.f("fk_daily_plan_tasks_daily_plan_id_daily_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_plan_tasks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_plan_tasks")
    # ### end Alembic commands ###
