"""Add recipe tasks

Revision ID: 642a49893a64
Revises: 6ad5e2929436
Create Date: 2022-05-26 14:58:27.336896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "642a49893a64"
down_revision = "6ad5e2929436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("days_before_cooking", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tasks_recipe_id_recipes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_tasks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_tasks")
    # ### end Alembic commands ###
