"""Make ingredient loggable

Revision ID: 8ee949e8722c
Revises: 610e71d73c69
Create Date: 2023-06-28 20:18:39.655422

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8ee949e8722c"
down_revision = "610e71d73c69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("updated_by", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_ingredients_updated_by_users"),
            "users",
            ["updated_by"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_ingredients_updated_by_users"), type_="foreignkey"
        )
        batch_op.drop_column("updated_by")
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
