"""Prepare loggable ingredient

Revision ID: 610e71d73c69
Revises: 93034edd5318
Create Date: 2023-06-28 19:42:52.434712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "610e71d73c69"
down_revision = "93034edd5318"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        UPDATE ingredients
            SET created_at = '2000-01-01 00:00:00'
            WHERE created_at IS NULL;
        """
    )

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at", existing_type=mysql.DATETIME(), nullable=False
        )
        batch_op.drop_column("last_updated_at")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_updated_at", mysql.DATETIME(), nullable=True)
        )
        batch_op.alter_column(
            "created_at", existing_type=mysql.DATETIME(), nullable=True
        )

    # ### end Alembic commands ###
