"""Make events loggable

Revision ID: 93034edd5318
Revises: fd4a791d83c8
Create Date: 2023-06-23 20:50:47.802558

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "93034edd5318"
down_revision = "fd4a791d83c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("updated_by", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_events_updated_by_users"), "users", ["updated_by"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_events_updated_by_users"), type_="foreignkey"
        )
        batch_op.drop_column("updated_by")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
