"""Make amount optional

Revision ID: fd4a791d83c8
Revises: 330f10a28e03
Create Date: 2023-06-12 10:56:54.093853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fd4a791d83c8"
down_revision = "330f10a28e03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("recipes_have_ingredients", schema=None) as batch_op:
        batch_op.alter_column("amount", existing_type=mysql.FLOAT(), nullable=True)
        batch_op.drop_column("_is_measured")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes_have_ingredients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "_is_measured",
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column("amount", existing_type=mysql.FLOAT(), nullable=False)

    # ### end Alembic commands ###
