"""Use User model v3

Revision ID: 330f10a28e03
Revises: 2ddeb48032ef
Create Date: 2023-05-18 20:54:53.306743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_security

# revision identifiers, used by Alembic.
revision = "330f10a28e03"
down_revision = "2ddeb48032ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True
            )
        )
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=255), nullable=True
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_users_fs_webauthn_user_handle"), ["fs_webauthn_user_handle"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_users_us_phone_number"), ["us_phone_number"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_us_phone_number"), type_="unique")
        batch_op.drop_constraint(
            batch_op.f("uq_users_fs_webauthn_user_handle"), type_="unique"
        )
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=255), nullable=False
        )
        batch_op.drop_column("mf_recovery_codes")
        batch_op.drop_column("fs_webauthn_user_handle")
    # ### end Alembic commands ###
